apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: shell
  name: shell
spec:
  replicas: 1
  selector:
    run: shell
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: shell
    spec:
      containers:
      - image: python:2.7
        name: shell
        resources: {}
status:
  replicas: 0
