apiVersion: v1
kind: ReplicationController
metadata:
  name: sort-rc
spec:
  replicas: 1
  selector:
      name: shell-sort
  template:
    metadata:
      labels:
        name: shell-sort
    spec:
      containers:
      - image: python:2.7
        name: ls
        ports:
          - containerPort: 8000
        command:
          - /bin/sh
          - -c
          - "mkdir sortout ; curl -s 10.0.3.13:1025 | sort -r > sortout/index.html ; cd sortout ; python -m SimpleHTTPServer"
