apiVersion: v1
kind: ReplicationController
metadata:
  name: ls-rc
spec:
  replicas: 1
  selector:
      name: shell-ls
  template:
    metadata:
      labels:
        name: shell-ls
    spec:
      containers:
      - image: python:2.7
        name: ls
        ports:
          - containerPort: 8000
        command:
          - /bin/sh
          - -c
          - "python -m SimpleHTTPServer"
